// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Luis Fernando Rodriguez Llanos",
            "url": "https://www.linkedin.com/in/lrodriguez031/",
            "email": "luisrodriguez031@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "This API returns a list of items that user can buy given the user's fav item list and a coupon.\nThe total of item list cannot exceed the amount of the coupon",
                "produces": [
                    "application/json"
                ],
                "summary": "Returns a list of items from user's fav item list that can buy with a coupon",
                "parameters": [
                    {
                        "description": "Request body example",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InputData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutputData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.InputData": {
            "description": "User's request with the favorite list of items and the coupon total.",
            "type": "object",
            "required": [
                "amount",
                "item_ids"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 500000
                },
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "MCO516264975",
                        "MCO468600670",
                        "MCO451957965",
                        "MCO612637712",
                        "MCO869692087"
                    ]
                }
            }
        },
        "models.OutputData": {
            "description": "Response with the list of items that the user can buy and the total expended on those items.",
            "type": "object",
            "properties": {
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "MCO451957965",
                        "MCO468600670"
                    ]
                },
                "total": {
                    "type": "number",
                    "example": 470000
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/coupon/",
	Schemes:          []string{},
	Title:            "Mercadolibre coupon API",
	Description:      "Returns items that client can buy with a coupon.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
